name: Create Bucket

on: [push]

jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "auth GCP"
        uses: "google-github-actions/auth@v1"
        with: 
          credentials_json: "${{ secrets.GCP_TOKEN }}"


      - name: "npm install"
        run: npm install

      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Change to pulumi directory
        run: cd pulumi

      - name: "exec pulumi"
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: marciosw/quickstart/devlinux
        env: 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}


my Pulumi.yaml is in pulumi folder, so I included run to "cd pulumi" as you can see above, but the error still hapens:

Successfully authenticated
0s
Run cd pulumi
  
4s
Run pulumi/actions@v3
  
Configured range: ^3
Matched version: v3.129.0
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/53435c16-55e7-480c-be19-aafe6878fa89
Logging into the Pulumi Service backend.
Error: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack select --stack marciosw/quickstart/devlinux --non-interactive
error: no Pulumi.yaml project file found (searching upwards from /home/runner/work/sample-pulumi/sample-pulumi). If you have not created a project yet, use `pulumi new` to do so: no project file found
 err?: Error: Command failed with exit code 255: pulumi stack select --stack marciosw/quickstart/devlinux --non-interactive
error: no Pulumi.yaml project file found (searching upwards from /home/runner/work/sample-pulumi/sample-pulumi). If you have not created a project yet, use `pulumi new` to do so: no project file found


