name: Deploy Cloud Run

on: [push]

jobs: 

  testing-action:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pulumi

    steps: 
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "auth GCP"
        uses: "google-github-actions/auth@v1"
        with: 
          credentials_json: "${{ secrets.GCP_TOKEN }}"

      - name: "npm install"
        run: npm install

      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Verify Folder"
        run: pwd

      - name: "Verify Content"
        run: ls

      - name: "exec pulumi" # This should now work correctly!
        uses: pulumi/actions@v3
        with:
          command: preview 
          stack-name: marciosw/quickstart/devlinux
          workDir: ${{ github.workspace }}/pulumi # Specify the working 
        env: 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}

//------------

Im using script above in my actions.yml, under a angular project. When I push it to github Im facing the following error:

...

Run google-github-actions/setup-gcloud@v1
  
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/ba8619d5-a6ec-4826-b2a5-2991d7e68091 -f /home/runner/work/_temp/a36ae4d2-d39b-4567-876c-de73b4b16a90
Successfully authenticated
0s
Run pwd
/home/runner/work/sample-pulumi/sample-pulumi/pulumi
0s
Run ls
Pulumi.devlinux.yaml
Pulumi.yaml
index.ts
node_modules
package-lock.json
package.json
tsconfig.json
4s
Run pulumi/actions@v3
  
Configured range: ^3
Matched version: v3.129.0
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/9f6ba8a5-fa28-4add-b589-94d734624bb9
Logging into the Pulumi Service backend.
Error: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack select --stack marciosw/quickstart/devlinux --non-interactive
error: no Pulumi.yaml project file found (searching upwards from /home/runner/work/sample-pulumi/sample-pulumi). If you have not created a project yet, use `pulumi new` to do so: no project file found
 err?: Error: Command failed with exit code 255: pulumi stack select --stack marciosw/quickstart/devlinux --non-interactive
error: no Pulumi.yaml project file found (searching upwards from /home/runner/work/sample-pulumi/sample-pulumi). If you have not created a project yet, use `pulumi new` to do so: no project file found
0s
Post job cleanup.
Removed exported credentials at "/home/runner/work/sample-pulumi/sample-pulumi/gha-creds-9e389fc363c4f99d.json".

....