name: Create Bucket

on: [push]

jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: "npm install"
        run: npm install

      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "exec pulumi"
        uses: pulumi/actions@v3
        with:
          pulumi-version: v3.128.0
      
      - name: "Deploy using Pulumi"
        run: pulumi preview --stack devlinux --non-interactive
        work-dir: ./pulumi   
        env: 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
