name: Deploy Cloud Run

on: [push]


jobs: 

  testing-action:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./pulumi # No longer strictly needed here

    steps: 
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "auth GCP"
        uses: "google-github-actions/auth@v1"
        with: 
          credentials_json: "${{ secrets.GCP_TOKEN }}"

      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      # --- Pulumi Specific Setup ---
      - name: "exec pulumi" # This should now work correctly!
        uses: pulumi/actions@v3
        with:
          command: up 
          stack-name: marciosw/quickstart/devlinux
        env: 
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}